version = 1
SPDX-PackageName = "mcp-teams-server"
SPDX-PackageSupplier = "2025 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-PackageDownloadLocation = "https://github.com/InditexTech/mcp-teams-server"

[[annotations]]
path = [
    ".gitignore",
    ".dockerignore",
    ".github/**",
    "*.md",
    ".python-version",
    "repolinter.json",
    "glama.json",
    "REUSE.toml",
    "pyproject.toml",
    "NOTICE",
    "Dockerfile",
    "doc/**",
    "app/*",
    "sample.env",
    "uv.lock",
]
SPDX-FileCopyrightText = "2025 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-License-Identifier = "Apache-2.0"