name: Pull Request verification

on:
  pull_request:

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Sync project
      - run: uv sync --frozen --all-extras --dev --python 3.10

      - name: Ruff format check
        run: uv run --no-sync ruff check .

  check-typing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Sync project
      - run: uv sync --frozen --all-extras --dev --python 3.10

      - name: Pyright type checking
        run: uv run --no-sync pyright

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Sync project
      - run: uv sync --frozen --all-extras --dev --python 3.10

      - name: Pyright type checking
        run: uv run pytest