name: Release

on:
  workflow_dispatch:
  pull_request:
    branches: [ $default-branch ]
    types:
      - closed

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'kind/release') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install UV
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Sync project
        run: uv sync --frozen --all-extras --dev --python 3.10

      - name: Retrieve version
        shell: bash
        run: |
          VERSION=$(uv run pyproject-info project.version | tr -d '"'); echo "VERSION=v$VERSION" >> "$GITHUB_ENV"

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag inditextech/mcp-teams-server:${{ env.VERSION }}

      - name: Login into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # TODO: publish docker image

      - name: Create Git Tag
        run: |
          git config user.email "ghbot@github.com"
          git config user.name "GitHub Bot"

          git tag -a "${{ env.VERSION }}" -m "Version ${{ env.VERSION }}"
          git push origin "${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e
        with:
          name: v${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true